spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/*/hosp/**
        - id: service-system
          uri: lb://service-system
          predicates:
            - Path=/*/system/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**
        - id: service-cmn
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
server:
  port: 8200



