server:
  port: 8201
spring:
  application:
    name: service-hosp
  datasource:
    username: root
    password: 190325
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guigu_syt_hosp?serverTimezone=Asia/Shanghai
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    mongodb:
      host: 192.168.184.25
      username: atguigu
      password: "190325"
      database: syt
      port: 27017

logging:
  level:

    root: info
    org:
      mongodb:
        driver:
          protocol:
            command: debug

  file:
    path: hosp


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl