server:
  port: 8201
spring:
  application:
    name: service-hosp
  datasource:
    username: root
    password: 190325
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guigu_syt_hosp?serverTimezone=Asia/Shanghai
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    mongodb:
      host: 101.43.162.188
      username: atguigu
      password: "190325"
      database: syt
      port: 27017

logging:
  level:

    root: info
    org:
      mongodb:
        driver:
          protocol:
            command: debug

  file:
    path: hosp


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  client:
    config:
      default:
        connect-timeout: 2000 #连接建立的超时时长，单位是ms，默认1s
        read-timeout: 2000 #处理请求的超时时间，单位是ms，默认为1s
  sentinel:
    enabled: true



